нояб. 22, 2023 12:13:28 AM lab5.CustomInputMismatchException logException
SEVERE: Произошло исключение!
java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at lab5.CustomInputMismatchException.main(CustomInputMismatchException.java:16)

